Wiktor
piolad/chat-app pull request #30
Opened 2024-04-24 17:24 UTC by wiktor423

changes to atvice-sessions and .yml file

2024-04-24 17:34 UTC, piolad requested changes

2024-04-24 17:34 UTC, piolad commented on docker-compose.yml
> +      - REDIS_URL=redis://redis:6379
good use of env vars 👍

2024-04-24 17:34 UTC, piolad commented on active-sessions/src/client.rs
> +    let channel = Channel::from_static("http://[::1]:50051")
isn't port 50051 taken by auth-service?
Please see docker-compose.yml, this can lead to errors. 

**I think it's best to change this port**

2024-04-25 09:12 UTC, merged

2024-04-25 11:22 UTC, jakublaz commented on docker-compose.yml
> +      - "8001:8001"
The port can be closer to others used