Connection between auth-service and active-sessions, small changes to browser-facade
piolad/chat-app pull request #42
Opened 2024-05-23 16:05 UTC by jakublaz

data validation done in browser-facade, connection  to get session id between auth-service and active-sessions is established

2024-05-23 20:51 UTC, piolad requested changes

2024-05-23 20:51 UTC, piolad commented on docker-compose.yml
it is not a good idea to use auth network here but rather use a new network

2024-05-23 20:51 UTC, piolad commented on auth-service/build.rs
it is not a good idea to modify this - will probably lead to conflicts with Wiktor working on his branch.

2024-05-23 20:51 UTC, piolad commented on active-sessions/src/main.rs
same as in auth-service/build.rs

2024-05-23 20:51 UTC, piolad commented on active-sessions/src/client.rs
see auth-service/build.rs

2024-05-23 20:51 UTC, piolad commented on active-sessions/Cargo.toml
same as in auth-service/build.rs

2024-05-23 20:51 UTC, piolad commented on active-sessions/Dockerfile
auth-service/build.rs

2024-05-23 20:51 UTC, piolad commented on active-sessions/proto/active-sessions.proto
auth-service/build.rs

2024-05-23 20:58 UTC, jakublaz commented on auth-service/build.rs
this is my service and wiktor is not working on this service i have made sure of it

2024-05-23 20:59 UTC, jakublaz commented on docker-compose.yml
ok we can do it, but to be consistient we should do it will all the databases. OK?

2024-05-23 21:01 UTC, jakublaz commented
I have made sure that wiktor is not working on this branch he is doing docs now for message-data-centre

2024-05-24 06:47 UTC, piolad approved these changes

2024-05-24 06:53 UTC, merged